language: node_js
node_js:
- '8.5.0'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
- npm install -g bower grunt-cli
- bower install
deploy:
- provider: s3
  access_key_id: AKIAIOXDFJYWRYJT36VA
  secret_access_key: &1
    secure: SBUIPHfVt7Alod3SqPGS2zxuysHIp3UzpEY6gzDC285qZa7wuix5ZTgTffm0f/rUkwSQtvEbWqQ47gLnLKQ89YoDL7w4MazUQBZNOe9cRwPafig1joKa+vDNH/MokWy4GWEXO4SUMU9ZZQwkWkR3YeG/ug/XJlmHhP1rZRGAjBU1ewKm1757HY/YusK6s6zxR+9UWgJTMDy0IrYTdmTB7GllMR3q5/pTk8+Z8hITfcYxFq0FsUUN5SP6MM8yleW7xcXii10/zOiQSWR7b2tXWTyygmQirg7o6GACc32SCtjrqQnmrQyYh/Rddutphxh2ltsJT4Q2PI9zxqFpAa6YIfzrNJPalBRHrKM9yIsZb+Sk2HYEVznJTQ4YfgQPShwwDYIby+XZtkOcjH/4KrAzJlTxLFoFLsbn9uo63kdDqb9F2mldHXmMbSdwHbVIzmyEcFvGgtghoS+ouWupw2iw+eF3a63T8z7eyuhjkH258y623ct8pM1NK9cZaYY8H+tUvNoehlmK/dYO0Nn2A88rZpTrEJ9qTYCbTOmGQAvwF2LqErosZ/T/7ObH7mKkeLvZz8ocQWsqQ52FK8e3L3qDYrCgc7Zt1eQmJquqf0uxUIG2qahAvgqiwc2EwWWP0/DJmttIxeHX299m5kFIRJ18wKDtQd1+eK5vwC7suRE4nyU=
  local_dir: dist
  skip_cleanup: true
  on: &2
    repo: Afshintm/myblog
    branch: feature/newAngularFire1
  bucket: afshinteymoori.com
  region: ap-southeast-2
  endpoint: afshinteymoori.com.s3-website-ap-southeast-2.amazonaws.com
  upload-dir: myblog
before_deploy:
- rvm 1.9.3 do gem install mime-types -v 2.6.2
- grunt build
addons:
  artifacts: true

